//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModelAndAnnotationAndValidation.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Email { get; set; }
        public System.DateTime JoinDate { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public int DesignationId { get; set; }
    
        public virtual Designation Designation { get; set; }
    }
}
