//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCModelAndAnnotationAndValidation.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWiseRole
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RoleId { get; set; }
    
        public virtual TblRole TblRole { get; set; }
        public virtual TblUser TblUser { get; set; }
    }
}
